version: "3"

services:
  postgres:
    image: postgres:11.4
    container_name: index_db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indexer
    ports:
      - 5432:5432

  app:
    image: node:14.16.1
    environment:
      KNEX_ENV: test
    container_name: index_app
    restart: on-failure:10 # necessary due to possibility of postgres not being ready when service runs
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    #command: ./scripts/run_tests.sh
    command: bash -c " npm install && npm run migrations && npm run seeds && npm run tests "
